import type { Locale } from "@/i18n/config";

export type MatchLabels = {
  overview:string; oracle:string; h2h:string; lineups:string; stats:string; relevantPatterns:string; eligibleFixtures:string; eligible:string;
  overall:string; home:string; away:string; oracleDecision:string; preMatch:string; referenceOdds:string; myPicks:string;
  historicalEvidence:string; matchStreaks:string; compareExplorer:string; evidenceHistory:string; previousMeetings:string; headToHead:string; lastFive:string; draw:string;
  seasonBaseline:string; teamComparison:string; leagueMatches:string; expectedXi:string; probableLineups:string; notConfirmed:string;
  searchPlaceholder:string; searchFootball:string; match:string; oracleAnalysis:string; teamStreaks:string; statistics:string;
  breadcrumb:string; removeSaved:string; saveMatch:string; scheduled:string; referee:string; matchSections:string;
  matchInformation:string; kickoff:string; venue:string; round:string; standings:string; team:string; played:string; points:string; fullStandings:string;
  evidenceNote:string; evidenceSignals:string; recentForm:string; allCompetitions:string; responsiblePlay:string; mobileNavigation:string;
  goalsPerMatch:string; expectedGoals:string; possession:string; shotsOnTarget:string; corners:string; cleanSheets:string;
  advertisement:string; viewH2hForm:string; viewLineupsPitch:string; viewFullStats:string; addToMultiPicks:string;
};

export const matchLabels: Record<Locale, MatchLabels> = {
  en:{overview:"Overview",oracle:"Oracle",h2h:"H2H",lineups:"Lineups",stats:"Stats",relevantPatterns:"Relevant patterns",eligibleFixtures:"eligible fixtures",eligible:"eligible",overall:"Overall",home:"Home",away:"Away",oracleDecision:"Oracle decision",preMatch:"Pre-match",referenceOdds:"Reference odds",myPicks:"My Picks",historicalEvidence:"Historical evidence",matchStreaks:"Match streaks",compareExplorer:"Compare in explorer",evidenceHistory:"Runs are calculated independently by overall, home and away scope through the latest eligible completed fixture. They describe history, not a guaranteed continuation.",previousMeetings:"Previous meetings",headToHead:"Head to head",lastFive:"Last 5",draw:"Draw",seasonBaseline:"Season baseline",teamComparison:"Team comparison",leagueMatches:"League matches",expectedXi:"Expected XI",probableLineups:"Probable lineups",notConfirmed:"Not confirmed",searchPlaceholder:"Search teams, competitions or matches",searchFootball:"Search football",match:"Match",oracleAnalysis:"Oracle analysis",teamStreaks:"Team streaks",statistics:"Statistics",breadcrumb:"Breadcrumb",removeSaved:"Remove match from saved",saveMatch:"Save match",scheduled:"Scheduled",referee:"Referee",matchSections:"Match sections",matchInformation:"Match information",kickoff:"Kickoff",venue:"Venue",round:"Round",standings:"Standings",team:"Team",played:"P",points:"Pts",fullStandings:"Full standings",evidenceNote:"Evidence note",evidenceSignals:"Streaks use eligible completed fixtures strictly before this match. Prediction and historical evidence remain separate signals.",recentForm:"recent form",allCompetitions:"All competitions",responsiblePlay:"Responsible play",mobileNavigation:"Mobile navigation",goalsPerMatch:"Goals per match",expectedGoals:"Expected goals",possession:"Possession",shotsOnTarget:"Shots on target",corners:"Corners",cleanSheets:"Clean sheets",advertisement:"Advertisement",viewH2hForm:"View Head-to-Head & Recent Form",viewLineupsPitch:"View Lineups & Formations",viewFullStats:"View Detailed Match Statistics",addToMultiPicks:"Add to Multi-Picks"},
  es:{overview:"Resumen",oracle:"Oracle",h2h:"H2H",lineups:"Alineaciones",stats:"Estadísticas",relevantPatterns:"Patrones relevantes",eligibleFixtures:"partidos válidos",eligible:"válidos",overall:"General",home:"Local",away:"Visitante",oracleDecision:"Decisión de Oracle",preMatch:"Antes del partido",referenceOdds:"Cuotas de referencia",myPicks:"Mis selecciones",historicalEvidence:"Evidencia histórica",matchStreaks:"Rachas del partido",compareExplorer:"Comparar en el explorador",evidenceHistory:"Las rachas se calculan por separado en los ámbitos general, local y visitante hasta el último partido válido completado. Describen el historial, no garantizan que continúen.",previousMeetings:"Enfrentamientos anteriores",headToHead:"Cara a cara",lastFive:"Últimos 5",draw:"Empate",seasonBaseline:"Referencia de la temporada",teamComparison:"Comparación de equipos",leagueMatches:"Partidos de liga",expectedXi:"Once previsto",probableLineups:"Alineaciones probables",notConfirmed:"Sin confirmar",searchPlaceholder:"Buscar equipos, competiciones o partidos",searchFootball:"Buscar fútbol",match:"Partido",oracleAnalysis:"Análisis de Oracle",teamStreaks:"Rachas de los equipos",statistics:"Estadísticas",breadcrumb:"Ruta de navegación",removeSaved:"Quitar el partido de Guardados",saveMatch:"Guardar partido",scheduled:"Programado",referee:"Árbitro",matchSections:"Secciones del partido",matchInformation:"Información del partido",kickoff:"Inicio",venue:"Estadio",round:"Jornada",standings:"Clasificación",team:"Equipo",played:"PJ",points:"Pts",fullStandings:"Clasificación completa",evidenceNote:"Nota sobre la evidencia",evidenceSignals:"Las rachas solo utilizan partidos válidos completados antes de este encuentro. La predicción y la evidencia histórica se mantienen como señales separadas.",recentForm:"forma reciente",allCompetitions:"Todas las competiciones",responsiblePlay:"Juego responsable",mobileNavigation:"Navegación móvil",goalsPerMatch:"Goles por partido",expectedGoals:"Goles esperados",possession:"Posesión",shotsOnTarget:"Tiros a puerta",corners:"Córneres",cleanSheets:"Porterías a cero",advertisement:"Publicidad",viewH2hForm:"Ver enfrentamientos directos y forma",viewLineupsPitch:"Ver alineaciones y formaciones",viewFullStats:"Ver estadísticas detalladas",addToMultiPicks:"Añadir a Multi-Picks"},
  fr:{overview:"Aperçu",oracle:"Oracle",h2h:"Confrontations",lineups:"Compositions",stats:"Statistiques",relevantPatterns:"Tendances pertinentes",eligibleFixtures:"matchs admissibles",eligible:"admissibles",overall:"Général",home:"Domicile",away:"Extérieur",oracleDecision:"Décision Oracle",preMatch:"Avant-match",referenceOdds:"Cotes de référence",myPicks:"Mes sélections",historicalEvidence:"Éléments historiques",matchStreaks:"Séries du match",compareExplorer:"Comparer dans l’explorateur",evidenceHistory:"Les séries sont calculées séparément pour l’ensemble des matchs, le domicile et l’extérieur, jusqu’au dernier match admissible terminé. Elles décrivent l’historique sans garantir sa continuité.",previousMeetings:"Confrontations précédentes",headToHead:"Face-à-face",lastFive:"5 derniers",draw:"Nul",seasonBaseline:"Repères de la saison",teamComparison:"Comparaison des équipes",leagueMatches:"Matchs de championnat",expectedXi:"Onze attendu",probableLineups:"Compositions probables",notConfirmed:"Non confirmées",searchPlaceholder:"Rechercher une équipe, une compétition ou un match",searchFootball:"Rechercher dans le football",match:"Match",oracleAnalysis:"Analyse Oracle",teamStreaks:"Séries des équipes",statistics:"Statistiques",breadcrumb:"Fil d’Ariane",removeSaved:"Retirer le match des favoris",saveMatch:"Enregistrer le match",scheduled:"Programmé",referee:"Arbitre",matchSections:"Sections du match",matchInformation:"Informations du match",kickoff:"Coup d’envoi",venue:"Stade",round:"Journée",standings:"Classement",team:"Équipe",played:"MJ",points:"Pts",fullStandings:"Classement complet",evidenceNote:"Note méthodologique",evidenceSignals:"Les séries utilisent uniquement les matchs admissibles terminés avant cette rencontre. La prédiction et l’historique restent deux signaux distincts.",recentForm:"forme récente",allCompetitions:"Toutes les compétitions",responsiblePlay:"Jeu responsable",mobileNavigation:"Navigation mobile",goalsPerMatch:"Buts par match",expectedGoals:"Buts attendus",possession:"Possession",shotsOnTarget:"Tirs cadrés",corners:"Corners",cleanSheets:"Matchs sans encaisser",advertisement:"Publicité",viewH2hForm:"Voir les confrontations directes et la forme",viewLineupsPitch:"Voir les compositions et tactiques",viewFullStats:"Voir les statistiques détaillées",addToMultiPicks:"Ajouter aux Multi-Picks"},
  de:{overview:"Übersicht",oracle:"Oracle",h2h:"Direktvergleich",lineups:"Aufstellungen",stats:"Statistiken",relevantPatterns:"Relevante Muster",eligibleFixtures:"geeignete Spiele",eligible:"geeignet",overall:"Gesamt",home:"Heim",away:"Auswärts",oracleDecision:"Oracle-Entscheidung",preMatch:"Vor dem Spiel",referenceOdds:"Referenzquoten",myPicks:"Meine Tipps",historicalEvidence:"Historische Datengrundlage",matchStreaks:"Spielserien",compareExplorer:"Im Explorer vergleichen",evidenceHistory:"Serien werden für Gesamt-, Heim- und Auswärtsspiele getrennt bis zum letzten geeigneten abgeschlossenen Spiel berechnet. Sie beschreiben den Verlauf und garantieren keine Fortsetzung.",previousMeetings:"Frühere Begegnungen",headToHead:"Direktvergleich",lastFive:"Letzte 5",draw:"Unentschieden",seasonBaseline:"Saisonvergleich",teamComparison:"Teamvergleich",leagueMatches:"Ligaspiele",expectedXi:"Erwartete Startelf",probableLineups:"Voraussichtliche Aufstellungen",notConfirmed:"Nicht bestätigt",searchPlaceholder:"Teams, Wettbewerbe oder Spiele suchen",searchFootball:"Fußball durchsuchen",match:"Spiel",oracleAnalysis:"Oracle-Analyse",teamStreaks:"Teamserien",statistics:"Statistiken",breadcrumb:"Navigationspfad",removeSaved:"Spiel aus Gespeichert entfernen",saveMatch:"Spiel speichern",scheduled:"Geplant",referee:"Schiedsrichter",matchSections:"Spielbereiche",matchInformation:"Spielinformationen",kickoff:"Anstoß",venue:"Stadion",round:"Spieltag",standings:"Tabelle",team:"Team",played:"Sp.",points:"Pkt.",fullStandings:"Vollständige Tabelle",evidenceNote:"Hinweis zur Datengrundlage",evidenceSignals:"Serien beruhen ausschließlich auf geeigneten abgeschlossenen Spielen vor dieser Begegnung. Prognose und historische Daten bleiben getrennte Signale.",recentForm:"aktuelle Form",allCompetitions:"Alle Wettbewerbe",responsiblePlay:"Verantwortungsvolles Spielen",mobileNavigation:"Mobile Navigation",goalsPerMatch:"Tore pro Spiel",expectedGoals:"Erwartete Tore",possession:"Ballbesitz",shotsOnTarget:"Torschüsse",corners:"Ecken",cleanSheets:"Spiele ohne Gegentor",advertisement:"Werbung",viewH2hForm:"Direktvergleich & aktuelle Form ansehen",viewLineupsPitch:"Aufstellungen & Formationen ansehen",viewFullStats:"Detaillierte Spielstatistiken ansehen",addToMultiPicks:"Zu Multi-Picks hinzufügen"},
  it:{overview:"Panoramica",oracle:"Oracle",h2h:"Precedenti",lineups:"Formazioni",stats:"Statistiche",relevantPatterns:"Tendenze rilevanti",eligibleFixtures:"partite idonee",eligible:"idonee",overall:"Generale",home:"Casa",away:"Trasferta",oracleDecision:"Decisione Oracle",preMatch:"Pre-partita",referenceOdds:"Quote di riferimento",myPicks:"Le mie selezioni",historicalEvidence:"Evidenze storiche",matchStreaks:"Serie della partita",compareExplorer:"Confronta nell’esploratore",evidenceHistory:"Le serie vengono calcolate separatamente per ambito generale, casa e trasferta fino all’ultima partita idonea conclusa. Descrivono lo storico, senza garantirne la prosecuzione.",previousMeetings:"Incontri precedenti",headToHead:"Scontri diretti",lastFive:"Ultimi 5",draw:"Pareggio",seasonBaseline:"Riferimento stagionale",teamComparison:"Confronto squadre",leagueMatches:"Partite di campionato",expectedXi:"Undici previsto",probableLineups:"Probabili formazioni",notConfirmed:"Non confermate",searchPlaceholder:"Cerca squadre, competizioni o partite",searchFootball:"Cerca nel calcio",match:"Partita",oracleAnalysis:"Analisi Oracle",teamStreaks:"Serie delle squadre",statistics:"Statistiche",breadcrumb:"Percorso di navigazione",removeSaved:"Rimuovi la partita dai Salvati",saveMatch:"Salva partita",scheduled:"In programma",referee:"Arbitro",matchSections:"Sezioni della partita",matchInformation:"Informazioni sulla partita",kickoff:"Calcio d’inizio",venue:"Stadio",round:"Giornata",standings:"Classifica",team:"Squadra",played:"G",points:"Pt",fullStandings:"Classifica completa",evidenceNote:"Nota sulle evidenze",evidenceSignals:"Le serie utilizzano solo partite idonee concluse prima di questo incontro. Il pronostico e le evidenze storiche restano segnali distinti.",recentForm:"forma recente",allCompetitions:"Tutte le competizioni",responsiblePlay:"Gioco responsabile",mobileNavigation:"Navigazione mobile",goalsPerMatch:"Gol per partita",expectedGoals:"Gol attesi",possession:"Possesso",shotsOnTarget:"Tiri in porta",corners:"Calci d’angolo",cleanSheets:"Partite senza subire gol",advertisement:"Pubblicità",viewH2hForm:"Vedi scontri diretti e forma recente",viewLineupsPitch:"Vedi formazioni e schieramenti",viewFullStats:"Vedi statistiche dettagliate della partita",addToMultiPicks:"Aggiungi a Multi-Picks"},
  pt:{overview:"Visão geral",oracle:"Oracle",h2h:"Confrontos",lineups:"Escalações",stats:"Estatísticas",relevantPatterns:"Padrões relevantes",eligibleFixtures:"jogos elegíveis",eligible:"elegíveis",overall:"Geral",home:"Casa",away:"Fora",oracleDecision:"Decisão do Oracle",preMatch:"Pré-jogo",referenceOdds:"Odds de referência",myPicks:"Minhas seleções",historicalEvidence:"Evidências históricas",matchStreaks:"Sequências do jogo",compareExplorer:"Comparar no explorador",evidenceHistory:"As sequências são calculadas separadamente nos recortes geral, casa e fora até o último jogo elegível concluído. Elas descrevem o histórico, sem garantir continuidade.",previousMeetings:"Confrontos anteriores",headToHead:"Confronto direto",lastFive:"Últimos 5",draw:"Empate",seasonBaseline:"Referência da temporada",teamComparison:"Comparação das equipes",leagueMatches:"Jogos da liga",expectedXi:"Onze esperado",probableLineups:"Escalações prováveis",notConfirmed:"Não confirmadas",searchPlaceholder:"Buscar times, competições ou jogos",searchFootball:"Buscar futebol",match:"Jogo",oracleAnalysis:"Análise do Oracle",teamStreaks:"Sequências dos times",statistics:"Estatísticas",breadcrumb:"Caminho de navegação",removeSaved:"Remover jogo dos Salvos",saveMatch:"Salvar jogo",scheduled:"Agendado",referee:"Árbitro",matchSections:"Seções do jogo",matchInformation:"Informações do jogo",kickoff:"Início",venue:"Estádio",round:"Rodada",standings:"Classificação",team:"Time",played:"J",points:"Pts",fullStandings:"Classificação completa",evidenceNote:"Nota sobre as evidências",evidenceSignals:"As sequências usam apenas jogos elegíveis concluídos antes desta partida. A previsão e as evidências históricas permanecem sinais distintos.",recentForm:"forma recente",allCompetitions:"Todas as competições",responsiblePlay:"Jogo responsável",mobileNavigation:"Navegação móvel",goalsPerMatch:"Gols por jogo",expectedGoals:"Gols esperados",possession:"Posse de bola",shotsOnTarget:"Finalizações no alvo",corners:"Escanteios",cleanSheets:"Jogos sem sofrer gols",advertisement:"Publicidade",viewH2hForm:"Ver confrontos diretos e forma recente",viewLineupsPitch:"Ver escalações e formações",viewFullStats:"Ver estatísticas detalhadas do jogo",addToMultiPicks:"Adicionar aos Multi-Picks"},
};

export function matchScopeLabel(locale: Locale, scope: MatchStreakScope) {
  const copy = matchLabels[locale];
  return scope === "OVERALL" ? copy.overall : scope === "HOME" ? copy.home : copy.away;
}

type MatchStreakScope = "OVERALL" | "HOME" | "AWAY";

export function matchStatLabel(locale: Locale, label: string) {
  const copy = matchLabels[locale];
  const labels: Record<string, string> = {
    "Goals per match": copy.goalsPerMatch,
    "Expected goals": copy.expectedGoals,
    Possession: copy.possession,
    "Shots on target": copy.shotsOnTarget,
    Corners: copy.corners,
    "Clean sheets": copy.cleanSheets,
  };
  return labels[label] ?? label;
}
