import type { Locale } from "./config";

type SystemLabels={loading:string;errorTitle:string;errorDescription:string;retry:string;todayDescription:string;tomorrowDescription:string;matchTitle:string;matchDescription:string};
export const systemLabels:Record<Locale,SystemLabels>={
 en:{loading:"Loading",errorTitle:"This view could not be loaded",errorDescription:"Your filters and saved items are unchanged. Retry the request to restore this page.",retry:"Retry",todayDescription:"Today's football fixtures, predictions and match intelligence in one place.",tomorrowDescription:"Tomorrow's football fixtures, predictions and match intelligence, published a day ahead of kick-off.",matchTitle:"{home} vs {away}: prediction and streaks",matchDescription:"{home} vs {away} preview with the Oracle prediction, verified team streaks, form, head-to-head record, probable lineups and statistics."},
 es:{loading:"Cargando",errorTitle:"No se ha podido cargar esta vista",errorDescription:"Tus filtros y elementos guardados no han cambiado. Vuelve a intentarlo para recuperar la página.",retry:"Reintentar",todayDescription:"Partidos, pronósticos y análisis de fútbol de hoy en un solo lugar.",tomorrowDescription:"Partidos, pronósticos y análisis de fútbol de mañana, publicados con un día de antelación.",matchTitle:"{home} vs {away}: pronóstico y rachas",matchDescription:"Previa de {home} vs {away} con el pronóstico Oracle, rachas verificadas, forma, enfrentamientos directos, posibles alineaciones y estadísticas."},
 fr:{loading:"Chargement",errorTitle:"Impossible de charger cette page",errorDescription:"Vos filtres et éléments enregistrés sont inchangés. Réessayez pour rétablir la page.",retry:"Réessayer",todayDescription:"Matchs, pronostics et analyses football du jour au même endroit.",tomorrowDescription:"Matchs, pronostics et analyses football de demain, publiés un jour à l’avance.",matchTitle:"{home} - {away} : pronostic et séries",matchDescription:"Avant-match de {home} - {away} avec le pronostic Oracle, les séries vérifiées, la forme, les confrontations, les compositions probables et les statistiques."},
 de:{loading:"Wird geladen",errorTitle:"Diese Ansicht konnte nicht geladen werden",errorDescription:"Deine Filter und gespeicherten Inhalte sind unverändert. Versuche erneut, die Seite zu laden.",retry:"Erneut versuchen",todayDescription:"Heutige Fußballspiele, Prognosen und Spielanalysen an einem Ort.",tomorrowDescription:"Fußballspiele, Prognosen und Spielanalysen für morgen, einen Tag vor Anstoß veröffentlicht.",matchTitle:"{home} gegen {away}: Prognose und Serien",matchDescription:"Vorschau auf {home} gegen {away} mit Oracle-Prognose, verifizierten Teamserien, Form, direktem Vergleich, voraussichtlichen Aufstellungen und Statistiken."},
 it:{loading:"Caricamento",errorTitle:"Impossibile caricare questa pagina",errorDescription:"I filtri e gli elementi salvati non sono cambiati. Riprova per ripristinare la pagina.",retry:"Riprova",todayDescription:"Partite, pronostici e analisi calcistiche di oggi in un unico posto.",tomorrowDescription:"Partite, pronostici e analisi calcistiche di domani, pubblicati con un giorno di anticipo.",matchTitle:"{home} - {away}: pronostico e serie",matchDescription:"Anteprima di {home} - {away} con pronostico Oracle, serie verificate, forma, precedenti, probabili formazioni e statistiche."},
 pt:{loading:"Carregando",errorTitle:"Não foi possível carregar esta página",errorDescription:"Seus filtros e itens salvos não foram alterados. Tente novamente para restaurar a página.",retry:"Tentar novamente",todayDescription:"Jogos, palpites e análises de futebol de hoje em um só lugar.",tomorrowDescription:"Jogos, palpites e análises de futebol de amanhã, publicados com um dia de antecedência.",matchTitle:"{home} x {away}: palpite e sequências",matchDescription:"Prévia de {home} x {away} com o palpite Oracle, sequências verificadas, forma, confrontos diretos, prováveis escalações e estatísticas."}
};

export function interpolateSystem(value:string,fields:Record<string,string>){return Object.entries(fields).reduce((text,[key,replacement])=>text.replaceAll(`{${key}}`,replacement),value)}
