import type { Locale } from '@/i18n/config';
const words = {
  en: ['Market intelligence', 'Pre-match', 'In-play', 'Model probability', 'Recorded odds', 'Line', 'Building evidence', 'Live estimates unavailable', 'Delayed', 'Updated', 'matches per team', 'Home', 'Draw', 'Away', 'Over', 'Under', 'Yes', 'No', 'Yellow + red cards; bookmaker rules may differ.', 'Estimated edge', 'Higher-probability selections with positive value.', 'Selections ranked by estimated pricing advantage.', 'All predictions', 'First half', 'Full time', 'No qualifying selections', 'Rankings are being prepared'],
  es: ['Análisis del mercado', 'Prepartido', 'En directo', 'Probabilidad del modelo', 'Cuotas registradas', 'Línea', 'Recopilando datos', 'Estimaciones en directo no disponibles', 'Con retraso', 'Actualizado', 'partidos por equipo', 'Local', 'Empate', 'Visitante', 'Más de', 'Menos de', 'Sí', 'No', 'Tarjetas amarillas + rojas; las reglas pueden variar.', 'Ventaja estimada', 'Selecciones de mayor probabilidad con valor positivo.', 'Selecciones ordenadas por ventaja estimada en las cuotas.', 'Todas las predicciones', 'Primera parte', 'Final', 'No hay selecciones que cumplan los criterios', 'Se están preparando las clasificaciones'],
  fr: ['Analyse du marché', 'Avant-match', 'En direct', 'Probabilité du modèle', 'Cotes enregistrées', 'Seuil', 'Collecte des données', 'Estimations en direct indisponibles', 'En retard', 'Actualisé', 'matchs par équipe', 'Domicile', 'Nul', 'Extérieur', 'Plus de', 'Moins de', 'Oui', 'Non', 'Cartons jaunes + rouges ; les règles peuvent varier.', 'Avantage estimé', 'Sélections plus probables présentant une valeur positive.', 'Sélections classées selon l’avantage estimé des cotes.', 'Toutes les prédictions', 'Mi-temps', 'Fin du match', 'Aucune sélection ne remplit les critères', 'Classements en préparation'],
  de: ['Marktanalyse', 'Vor dem Spiel', 'Live', 'Modellwahrscheinlichkeit', 'Erfasste Quoten', 'Linie', 'Datengrundlage im Aufbau', 'Live-Schätzungen nicht verfügbar', 'Verzögert', 'Aktualisiert', 'Spiele pro Team', 'Heim', 'Remis', 'Auswärts', 'Über', 'Unter', 'Ja', 'Nein', 'Gelbe + rote Karten; Anbieterregeln können abweichen.', 'Geschätzter Vorteil', 'Wahrscheinlichere Auswahlen mit positivem Wert.', 'Auswahlen nach geschätztem Quotenvorteil geordnet.', 'Alle Prognosen', 'Halbzeit', 'Spielende', 'Keine passenden Auswahlen', 'Ranglisten werden vorbereitet'],
  it: ['Analisi del mercato', 'Prepartita', 'In diretta', 'Probabilità del modello', 'Quote registrate', 'Soglia', 'Raccolta dei dati', 'Stime in diretta non disponibili', 'In ritardo', 'Aggiornato', 'partite per squadra', 'Casa', 'Pareggio', 'Ospite', 'Oltre', 'Meno di', 'Sì', 'No', 'Cartellini gialli + rossi; le regole possono variare.', 'Vantaggio stimato', 'Selezioni più probabili con valore positivo.', 'Selezioni ordinate per vantaggio stimato delle quote.', 'Tutte le previsioni', 'Primo tempo', 'Fine partita', 'Nessuna selezione soddisfa i criteri', 'Classifiche in preparazione'],
  pt: ['Análise do mercado', 'Pré-jogo', 'Ao vivo', 'Probabilidade do modelo', 'Odds registradas', 'Linha', 'Coletando dados', 'Estimativas ao vivo indisponíveis', 'Com atraso', 'Atualizado', 'jogos por equipe', 'Casa', 'Empate', 'Visitante', 'Mais de', 'Menos de', 'Sim', 'Não', 'Cartões amarelos + vermelhos; as regras podem variar.', 'Vantagem estimada', 'Seleções mais prováveis com valor positivo.', 'Seleções ordenadas pela vantagem estimada nas odds.', 'Todas as previsões', 'Primeiro tempo', 'Fim do jogo', 'Nenhuma seleção atende aos critérios', 'Classificações em preparação'],
} satisfies Record<Locale, string[]>;
export const intelligenceCopy = (locale: Locale) => words[locale];
