import type { Locale } from "@/i18n/config";

export type BetslipLabels = {
  searchPlaceholder: string; todaySlip: string; pastSlips: string; accumulators: string;
  eyebrow: string; title: string; subtitle: string; saved: string; save: string; share: string;
  dailyBetslip: string; totalOdds: string; target: string; selections: string; onePickPerFixture: string;
  averageOracle: string; legAverage: string; published: string; oddsSnapshot: string;
  immutableNote: string; fixtures: string; referenceOdds: string; selection: string; mixed: string; regular: string;
  odds: string; openMatch: string; slipStandard: string; targetOdds: string; markets: string;
  mixedThenRegular: string; teamOverlap: string; notAllowed: string; maximumLegs: string;
  recentSlips: string; picks: string; viewHistory: string; moreCombinations: string;
  dailyWeeklyAccas: string; openAccas: string; previousDate: string; nextDate: string;
  unavailableTitle: string; unavailableHelp: string; noPublicationTitle: string; noPublicationHelp: string;
  viewTodaysMatches: string; openMultiPicks: string; advertisement: string;
};

export const betslipLabels: Record<Locale, BetslipLabels> = {
  en: { searchPlaceholder:"Search teams, leagues or picks",todaySlip:"Today's slip",pastSlips:"Past slips",accumulators:"Accas",eyebrow:"DAILY PUBLICATION",title:"Today's Betslip",subtitle:"One focused daily combination from regular and mixed Oracle markets.",saved:"Saved",save:"Save",share:"Share",dailyBetslip:"Daily Betslip",totalOdds:"Total odds",target:"Target",selections:"Selections",onePickPerFixture:"One pick per fixture",averageOracle:"Average Oracle",legAverage:"Average across selections",published:"Published",oddsSnapshot:"Odds captured at publication",immutableNote:"Published selections and odds remain unchanged after kick-off.",fixtures:"fixtures",referenceOdds:"SportyBet reference odds",selection:"Selection",mixed:"Mixed",regular:"Regular",odds:"Odds",openMatch:"Open {home} versus {away}",slipStandard:"Betslip standard",targetOdds:"Target odds",markets:"Markets",mixedThenRegular:"Mixed first, then regular",teamOverlap:"Team overlap",notAllowed:"Not allowed",maximumLegs:"Maximum selections",recentSlips:"Recent betslips",picks:"picks",viewHistory:"View complete history",moreCombinations:"More combinations",dailyWeeklyAccas:"Daily and weekly Accas",openAccas:"Open Accas",previousDate:"Previous date",nextDate:"Next date",unavailableTitle:"Oracle Daily is temporarily unavailable",unavailableHelp:"The verified publication could not be retrieved safely. Nothing unverified will be shown in its place.",noPublicationTitle:"No Oracle Daily publication today",noPublicationHelp:"No combination met the strict 3.00–3.99 publication standard. The thresholds remain unchanged.",viewTodaysMatches:"View today's matches",openMultiPicks:"Open Multi-Picks",advertisement:"Advertisement" },
  es: { searchPlaceholder:"Buscar equipos, competiciones o pronósticos",todaySlip:"Cupón de hoy",pastSlips:"Cupones anteriores",accumulators:"Accas",eyebrow:"PUBLICACIÓN DIARIA",title:"Cupón de hoy",subtitle:"Una combinación diaria seleccionada entre los mercados regulares y mixtos de Oracle.",saved:"Guardado",save:"Guardar",share:"Compartir",dailyBetslip:"Cupón diario",totalOdds:"Cuota total",target:"Objetivo",selections:"Selecciones",onePickPerFixture:"Una selección por partido",averageOracle:"Oracle medio",legAverage:"Media de las selecciones",published:"Publicado",oddsSnapshot:"Cuotas registradas al publicar",immutableNote:"Las selecciones y cuotas publicadas no cambian después del inicio.",fixtures:"partidos",referenceOdds:"Cuotas de referencia de SportyBet",selection:"Selección",mixed:"Mixto",regular:"Regular",odds:"Cuota",openMatch:"Abrir {home} contra {away}",slipStandard:"Criterios del cupón",targetOdds:"Cuota objetivo",markets:"Mercados",mixedThenRegular:"Primero mixtos, después regulares",teamOverlap:"Equipos repetidos",notAllowed:"No permitido",maximumLegs:"Máximo de selecciones",recentSlips:"Cupones recientes",picks:"pronósticos",viewHistory:"Ver historial completo",moreCombinations:"Más combinaciones",dailyWeeklyAccas:"Accas diarias y semanales",openAccas:"Abrir Accas",previousDate:"Fecha anterior",nextDate:"Fecha siguiente",unavailableTitle:"Oracle Daily no está disponible temporalmente",unavailableHelp:"No se pudo recuperar la publicación verificada de forma segura. No se mostrará nada sin verificar en su lugar.",noPublicationTitle:"Hoy no hay publicación de Oracle Daily",noPublicationHelp:"Ninguna combinación alcanzó el estándar estricto de publicación de 3.00–3.99. Los umbrales no han cambiado.",viewTodaysMatches:"Ver los partidos de hoy",openMultiPicks:"Abrir Multi-Picks",advertisement:"Publicidad" },
  fr: { searchPlaceholder:"Rechercher des équipes, compétitions ou pronostics",todaySlip:"Coupon du jour",pastSlips:"Coupons précédents",accumulators:"Accas",eyebrow:"PUBLICATION DU JOUR",title:"Coupon du jour",subtitle:"Une combinaison quotidienne ciblée parmi les marchés Oracle classiques et mixtes.",saved:"Enregistré",save:"Enregistrer",share:"Partager",dailyBetslip:"Coupon quotidien",totalOdds:"Cote totale",target:"Objectif",selections:"Sélections",onePickPerFixture:"Une sélection par match",averageOracle:"Oracle moyen",legAverage:"Moyenne des sélections",published:"Publié",oddsSnapshot:"Cotes relevées à la publication",immutableNote:"Les sélections et les cotes publiées restent inchangées après le coup d’envoi.",fixtures:"matchs",referenceOdds:"Cotes SportyBet de référence",selection:"Sélection",mixed:"Mixte",regular:"Classique",odds:"Cote",openMatch:"Ouvrir {home} contre {away}",slipStandard:"Critères du coupon",targetOdds:"Cote cible",markets:"Marchés",mixedThenRegular:"Mixtes en priorité, puis classiques",teamOverlap:"Équipe présente plusieurs fois",notAllowed:"Non autorisé",maximumLegs:"Nombre maximal de sélections",recentSlips:"Coupons récents",picks:"pronostics",viewHistory:"Voir tout l’historique",moreCombinations:"Autres combinaisons",dailyWeeklyAccas:"Accas quotidiennes et hebdomadaires",openAccas:"Ouvrir les Accas",previousDate:"Date précédente",nextDate:"Date suivante",unavailableTitle:"Oracle Daily est temporairement indisponible",unavailableHelp:"La publication vérifiée n’a pas pu être récupérée en toute sécurité. Rien de non vérifié ne sera affiché à la place.",noPublicationTitle:"Aucune publication Oracle Daily aujourd’hui",noPublicationHelp:"Aucune combinaison n’a atteint le seuil strict de publication de 3.00–3.99. Les seuils restent inchangés.",viewTodaysMatches:"Voir les matchs du jour",openMultiPicks:"Ouvrir Multi-Picks",advertisement:"Publicité" },
  de: { searchPlaceholder:"Teams, Wettbewerbe oder Tipps suchen",todaySlip:"Heutiger Wettschein",pastSlips:"Frühere Wettscheine",accumulators:"Accas",eyebrow:"TÄGLICHE VERÖFFENTLICHUNG",title:"Heutiger Wettschein",subtitle:"Eine gezielte Tageskombination aus regulären und gemischten Oracle-Märkten.",saved:"Gespeichert",save:"Speichern",share:"Teilen",dailyBetslip:"Tageswettschein",totalOdds:"Gesamtquote",target:"Ziel",selections:"Tipps",onePickPerFixture:"Ein Tipp pro Spiel",averageOracle:"Oracle-Durchschnitt",legAverage:"Durchschnitt aller Tipps",published:"Veröffentlicht",oddsSnapshot:"Quotenstand bei Veröffentlichung",immutableNote:"Veröffentlichte Tipps und Quoten bleiben nach dem Anstoß unverändert.",fixtures:"Spiele",referenceOdds:"SportyBet-Referenzquoten",selection:"Tipp",mixed:"Gemischt",regular:"Regulär",odds:"Quote",openMatch:"{home} gegen {away} öffnen",slipStandard:"Wettschein-Kriterien",targetOdds:"Zielquote",markets:"Märkte",mixedThenRegular:"Zuerst gemischt, dann regulär",teamOverlap:"Team mehrfach enthalten",notAllowed:"Nicht zulässig",maximumLegs:"Maximale Tippanzahl",recentSlips:"Letzte Wettscheine",picks:"Tipps",viewHistory:"Gesamten Verlauf ansehen",moreCombinations:"Weitere Kombinationen",dailyWeeklyAccas:"Tägliche und wöchentliche Accas",openAccas:"Accas öffnen",previousDate:"Vorheriges Datum",nextDate:"Nächstes Datum",unavailableTitle:"Oracle Daily ist vorübergehend nicht verfügbar",unavailableHelp:"Die verifizierte Veröffentlichung konnte nicht sicher abgerufen werden. Es wird nichts Unverifiziertes stattdessen angezeigt.",noPublicationTitle:"Heute keine Oracle-Daily-Veröffentlichung",noPublicationHelp:"Keine Kombination erfüllte den strengen Veröffentlichungsstandard von 3,00–3,99. Die Schwellenwerte bleiben unverändert.",viewTodaysMatches:"Heutige Spiele ansehen",openMultiPicks:"Multi-Picks öffnen",advertisement:"Werbung" },
  it: { searchPlaceholder:"Cerca squadre, competizioni o pronostici",todaySlip:"Schedina di oggi",pastSlips:"Schedine precedenti",accumulators:"Accas",eyebrow:"PUBBLICAZIONE GIORNALIERA",title:"Schedina di oggi",subtitle:"Una combinazione giornaliera mirata dai mercati Oracle regolari e misti.",saved:"Salvata",save:"Salva",share:"Condividi",dailyBetslip:"Schedina giornaliera",totalOdds:"Quota totale",target:"Obiettivo",selections:"Selezioni",onePickPerFixture:"Una selezione per partita",averageOracle:"Media Oracle",legAverage:"Media delle selezioni",published:"Pubblicata",oddsSnapshot:"Quote rilevate alla pubblicazione",immutableNote:"Le selezioni e le quote pubblicate restano invariate dopo il calcio d’inizio.",fixtures:"partite",referenceOdds:"Quote SportyBet di riferimento",selection:"Selezione",mixed:"Misto",regular:"Regolare",odds:"Quota",openMatch:"Apri {home} contro {away}",slipStandard:"Criteri della schedina",targetOdds:"Quota obiettivo",markets:"Mercati",mixedThenRegular:"Prima misti, poi regolari",teamOverlap:"Squadra ripetuta",notAllowed:"Non consentita",maximumLegs:"Numero massimo di selezioni",recentSlips:"Schedine recenti",picks:"pronostici",viewHistory:"Vedi lo storico completo",moreCombinations:"Altre combinazioni",dailyWeeklyAccas:"Accas giornaliere e settimanali",openAccas:"Apri Accas",previousDate:"Data precedente",nextDate:"Data successiva",unavailableTitle:"Oracle Daily non è temporaneamente disponibile",unavailableHelp:"Non è stato possibile recuperare in sicurezza la pubblicazione verificata. Non verrà mostrato nulla di non verificato al suo posto.",noPublicationTitle:"Nessuna pubblicazione Oracle Daily oggi",noPublicationHelp:"Nessuna combinazione ha raggiunto lo standard rigoroso di pubblicazione 3,00–3,99. Le soglie restano invariate.",viewTodaysMatches:"Vedi le partite di oggi",openMultiPicks:"Apri Multi-Picks",advertisement:"Pubblicità" },
  pt: { searchPlaceholder:"Buscar times, competições ou palpites",todaySlip:"Bilhete de hoje",pastSlips:"Bilhetes anteriores",accumulators:"Accas",eyebrow:"PUBLICAÇÃO DIÁRIA",title:"Bilhete de hoje",subtitle:"Uma combinação diária objetiva entre os mercados regulares e mistos do Oracle.",saved:"Salvo",save:"Salvar",share:"Compartilhar",dailyBetslip:"Bilhete diário",totalOdds:"Odd total",target:"Meta",selections:"Seleções",onePickPerFixture:"Uma seleção por jogo",averageOracle:"Média Oracle",legAverage:"Média das seleções",published:"Publicado",oddsSnapshot:"Odds registradas na publicação",immutableNote:"As seleções e odds publicadas permanecem inalteradas após o início do jogo.",fixtures:"jogos",referenceOdds:"Odds de referência da SportyBet",selection:"Seleção",mixed:"Misto",regular:"Regular",odds:"Odd",openMatch:"Abrir {home} contra {away}",slipStandard:"Critérios do bilhete",targetOdds:"Odd-alvo",markets:"Mercados",mixedThenRegular:"Primeiro mistos, depois regulares",teamOverlap:"Time repetido",notAllowed:"Não permitido",maximumLegs:"Máximo de seleções",recentSlips:"Bilhetes recentes",picks:"palpites",viewHistory:"Ver histórico completo",moreCombinations:"Mais combinações",dailyWeeklyAccas:"Accas diárias e semanais",openAccas:"Abrir Accas",previousDate:"Data anterior",nextDate:"Próxima data",unavailableTitle:"Oracle Daily está temporariamente indisponível",unavailableHelp:"Não foi possível recuperar a publicação verificada com segurança. Nada não verificado será exibido em seu lugar.",noPublicationTitle:"Nenhuma publicação do Oracle Daily hoje",noPublicationHelp:"Nenhuma combinação atingiu o padrão rigoroso de publicação de 3,00–3,99. Os limites permanecem inalterados.",viewTodaysMatches:"Ver os jogos de hoje",openMultiPicks:"Abrir Multi-Picks",advertisement:"Publicidade" },
};
