import "server-only";
import { cookies } from "next/headers";
import { authBffConfig } from "@/features/auth/bff";
import type { Locale } from "@/i18n/config";

export type SavedFixtureView={id:string;kickoffAt:string;statusCode:string;statusDetail:string|null;score:{home:number|null;away:number|null};competition:{name:string;countryCode:string|null};home:{name:string;emblemUrl:string|null};away:{name:string;emblemUrl:string|null};selection:string|null;oracleScore:number|null;odds:number|null;alertEnabled:boolean;available:boolean};
export type PreferenceState={locale:Locale;timezone:string;quietHours:{enabled:boolean;start:string;end:string};notifications:{kickoff:boolean;oracleUpdate:boolean;settlement:boolean;accumulatorResult:boolean;morningDigest:boolean;eveningRecap:boolean}};
export type SavedViewData={matches:SavedFixtureView[];multiPickCount:number;followingCount:number;preferences:PreferenceState|null};
type ApiPrediction={id:string;selectionLabel:string|null;marketType:string|null;confidenceScore:number|null;latestOdds:Array<{decimalOdds:number}>};
type ApiMatch={fixtureId:string;predictionRevisionId?:string|null;alertEnabled:boolean;fixture:null|{id:string;kickoffAt:string;statusCode:string;statusDetail:string|null;score:{home:number|null;away:number|null};competition:{displayName:string;countryCode:string|null};homeTeam:{displayName:string;emblemUrl:string|null};awayTeam:{displayName:string;emblemUrl:string|null};predictions:ApiPrediction[]}};
type ApiSaved={matches:ApiMatch[];multiPicks:unknown[];following:unknown[];preferences:unknown|null};

export async function getSavedView(locale:Locale):Promise<SavedViewData>{
  const jar=await cookies();const session=jar.get("mbo_session")?.value;if(!session)return {matches:[],multiPickCount:0,followingCount:0,preferences:null};
  const {baseUrl,serviceKey}=authBffConfig();const response=await fetch(`${baseUrl}/api/v3/saved?locale=${locale}`,{headers:{"X-MyBetOracle-V3-Key":serviceKey,Cookie:`mbo_session=${encodeURIComponent(session)}`},cache:"no-store",signal:AbortSignal.timeout(6000)});if(!response.ok)throw new Error("Saved state is temporarily unavailable");const api=await response.json() as ApiSaved;
  return {matches:api.matches.map(reference=>{const fixture=reference.fixture;if(!fixture)return {id:reference.fixtureId,kickoffAt:"",statusCode:"UNAVAILABLE",statusDetail:null,score:{home:null,away:null},competition:{name:"Fixture data unavailable",countryCode:null},home:{name:"Saved fixture",emblemUrl:null},away:{name:"Awaiting canonical data",emblemUrl:null},selection:null,oracleScore:null,odds:null,alertEnabled:reference.alertEnabled,available:false};const prediction=fixture.predictions.find(item=>item.id===reference.predictionRevisionId)||fixture.predictions.slice().sort((a,b)=>(b.confidenceScore||0)-(a.confidenceScore||0))[0];return {id:fixture.id,kickoffAt:fixture.kickoffAt,statusCode:fixture.statusCode,statusDetail:fixture.statusDetail,score:fixture.score,competition:{name:fixture.competition.displayName,countryCode:fixture.competition.countryCode},home:{name:fixture.homeTeam.displayName,emblemUrl:fixture.homeTeam.emblemUrl},away:{name:fixture.awayTeam.displayName,emblemUrl:fixture.awayTeam.emblemUrl},selection:prediction?.selectionLabel||prediction?.marketType||null,oracleScore:prediction?.confidenceScore??null,odds:prediction?.latestOdds?.[0]?.decimalOdds??null,alertEnabled:reference.alertEnabled,available:true}}),multiPickCount:api.multiPicks.length,followingCount:api.following.length,preferences:api.preferences as PreferenceState|null};
}
