import type { Locale } from '@/i18n/config';
type Copy = { season: string; results: string; recent: string; next: string; previous: string; empty: string;
  noTable: string; failed: string; retry: string; team: string; played: string; won: string; drawn: string; lost: string; goals: string; difference: string; points: string; form: string; finished: string; live: string; predictions: string };
export const competitionLabels: Record<Locale, Copy> = {
  en: { season: 'Season', results: 'Results', recent: 'Recent results', next: 'Next', previous: 'Previous', empty: 'No matches available in this view.', noTable: 'A table is not available for this competition and season.', failed: 'This section could not be loaded.', retry: 'Try again', team: 'Team', played: 'P', won: 'W', drawn: 'D', lost: 'L', goals: 'GF:GA', difference: 'GD', points: 'Pts', form: 'Form', finished: 'Full time', live: 'Live', predictions: 'Published predictions' },
  fr: { season: 'Saison', results: 'Résultats', recent: 'Derniers résultats', next: 'Suivant', previous: 'Précédent', empty: 'Aucun match disponible dans cette vue.', noTable: 'Aucun classement disponible pour cette compétition et cette saison.', failed: 'Impossible de charger cette section.', retry: 'Réessayer', team: 'Équipe', played: 'MJ', won: 'V', drawn: 'N', lost: 'D', goals: 'BP:BC', difference: 'Diff.', points: 'Pts', form: 'Forme', finished: 'Terminé', live: 'En direct', predictions: 'Pronostics publiés' },
  es: { season: 'Temporada', results: 'Resultados', recent: 'Últimos resultados', next: 'Siguiente', previous: 'Anterior', empty: 'No hay partidos disponibles en esta vista.', noTable: 'No hay clasificación disponible para esta competición y temporada.', failed: 'No se ha podido cargar esta sección.', retry: 'Reintentar', team: 'Equipo', played: 'PJ', won: 'G', drawn: 'E', lost: 'P', goals: 'GF:GC', difference: 'DG', points: 'Pts', form: 'Forma', finished: 'Finalizado', live: 'En directo', predictions: 'Pronósticos publicados' },
  de: { season: 'Saison', results: 'Ergebnisse', recent: 'Letzte Ergebnisse', next: 'Weiter', previous: 'Zurück', empty: 'In dieser Ansicht sind keine Spiele verfügbar.', noTable: 'Für diesen Wettbewerb und diese Saison ist keine Tabelle verfügbar.', failed: 'Dieser Bereich konnte nicht geladen werden.', retry: 'Erneut versuchen', team: 'Team', played: 'Sp', won: 'S', drawn: 'U', lost: 'N', goals: 'Tore', difference: 'Diff.', points: 'Pkt', form: 'Form', finished: 'Beendet', live: 'Live', predictions: 'Veröffentlichte Prognosen' },
  it: { season: 'Stagione', results: 'Risultati', recent: 'Ultimi risultati', next: 'Avanti', previous: 'Indietro', empty: 'Nessuna partita disponibile in questa vista.', noTable: 'Classifica non disponibile per questa competizione e stagione.', failed: 'Impossibile caricare questa sezione.', retry: 'Riprova', team: 'Squadra', played: 'PG', won: 'V', drawn: 'N', lost: 'P', goals: 'GF:GS', difference: 'DR', points: 'Pt', form: 'Forma', finished: 'Terminata', live: 'Live', predictions: 'Pronostici pubblicati' },
  pt: { season: 'Temporada', results: 'Resultados', recent: 'Últimos resultados', next: 'Próximo', previous: 'Anterior', empty: 'Nenhuma partida disponível nesta visualização.', noTable: 'Classificação indisponível para esta competição e temporada.', failed: 'Não foi possível carregar esta seção.', retry: 'Tentar novamente', team: 'Time', played: 'J', won: 'V', drawn: 'E', lost: 'D', goals: 'GP:GC', difference: 'SG', points: 'Pts', form: 'Forma', finished: 'Encerrado', live: 'Ao vivo', predictions: 'Palpites publicados' },
};
