import type { Locale } from '@/i18n/config';
type Copy = { season: string; results: string; recent: string; next: string; previous: string; empty: string;
  noTable: string; failed: string; retry: string; team: string; played: string; won: string; drawn: string; lost: string; goals: string; difference: string; points: string; form: string; finished: string; live: string; predictions: string;
  seoTitle: string; seoDescription: string; fixturesHeading: string; statisticsHeading: string;
  matchesPlayed: string; avgGoalsPerMatch: string; homeWin: string; draw: string; awayWin: string; btts: string; over15: string; over25: string; over35: string; avgHomeGoals: string; avgAwayGoals: string; statsUnavailable: string };
export const competitionLabels: Record<Locale, Copy> = {
  en: { season: 'Season', results: 'Results', recent: 'Recent results', next: 'Next', previous: 'Previous', empty: 'No matches available in this view.', noTable: 'A table is not available for this competition and season.', failed: 'This section could not be loaded.', retry: 'Try again', team: 'Team', played: 'P', won: 'W', drawn: 'D', lost: 'L', goals: 'GF:GA', difference: 'GD', points: 'Pts', form: 'Form', finished: 'Full time', live: 'Live', predictions: 'Published predictions',
    seoTitle: '{name} Predictions, Fixtures, Results & Stats', seoDescription: 'Explore {name} predictions, upcoming fixtures, recent results, standings and football statistics on MyBetOracle.', fixturesHeading: 'Fixtures', statisticsHeading: 'Statistics',
    matchesPlayed: 'Matches played', avgGoalsPerMatch: 'Avg. goals per match', homeWin: 'Home win', draw: 'Draw', awayWin: 'Away win', btts: 'Both teams to score', over15: 'Over 1.5 goals', over25: 'Over 2.5 goals', over35: 'Over 3.5 goals', avgHomeGoals: 'Avg. home goals', avgAwayGoals: 'Avg. away goals', statsUnavailable: 'Not enough settled matches yet this season for reliable statistics.' },
  fr: { season: 'Saison', results: 'Résultats', recent: 'Derniers résultats', next: 'Suivant', previous: 'Précédent', empty: 'Aucun match disponible dans cette vue.', noTable: 'Aucun classement disponible pour cette compétition et cette saison.', failed: 'Impossible de charger cette section.', retry: 'Réessayer', team: 'Équipe', played: 'MJ', won: 'V', drawn: 'N', lost: 'D', goals: 'BP:BC', difference: 'Diff.', points: 'Pts', form: 'Forme', finished: 'Terminé', live: 'En direct', predictions: 'Pronostics publiés',
    seoTitle: '{name} : Pronostics, Matchs, Résultats et Statistiques', seoDescription: 'Découvrez les pronostics, les prochains matchs, les derniers résultats, le classement et les statistiques de {name} sur MyBetOracle.', fixturesHeading: 'Calendrier', statisticsHeading: 'Statistiques',
    matchesPlayed: 'Matchs joués', avgGoalsPerMatch: 'Buts par match (moy.)', homeWin: 'Victoire à domicile', draw: 'Match nul', awayWin: 'Victoire à l’extérieur', btts: 'Les deux équipes marquent', over15: 'Plus de 1,5 but', over25: 'Plus de 2,5 buts', over35: 'Plus de 3,5 buts', avgHomeGoals: 'Buts à domicile (moy.)', avgAwayGoals: 'Buts à l’extérieur (moy.)', statsUnavailable: 'Pas encore assez de matchs joués cette saison pour des statistiques fiables.' },
  es: { season: 'Temporada', results: 'Resultados', recent: 'Últimos resultados', next: 'Siguiente', previous: 'Anterior', empty: 'No hay partidos disponibles en esta vista.', noTable: 'No hay clasificación disponible para esta competición y temporada.', failed: 'No se ha podido cargar esta sección.', retry: 'Reintentar', team: 'Equipo', played: 'PJ', won: 'G', drawn: 'E', lost: 'P', goals: 'GF:GC', difference: 'DG', points: 'Pts', form: 'Forma', finished: 'Finalizado', live: 'En directo', predictions: 'Pronósticos publicados',
    seoTitle: '{name}: Pronósticos, Partidos, Resultados y Estadísticas', seoDescription: 'Explora los pronósticos, próximos partidos, últimos resultados, clasificación y estadísticas de fútbol de {name} en MyBetOracle.', fixturesHeading: 'Próximos partidos', statisticsHeading: 'Estadísticas',
    matchesPlayed: 'Partidos jugados', avgGoalsPerMatch: 'Media de goles por partido', homeWin: 'Victoria local', draw: 'Empate', awayWin: 'Victoria visitante', btts: 'Ambos marcan', over15: 'Más de 1.5 goles', over25: 'Más de 2.5 goles', over35: 'Más de 3.5 goles', avgHomeGoals: 'Media de goles locales', avgAwayGoals: 'Media de goles visitantes', statsUnavailable: 'Todavía no hay suficientes partidos disputados esta temporada para estadísticas fiables.' },
  de: { season: 'Saison', results: 'Ergebnisse', recent: 'Letzte Ergebnisse', next: 'Weiter', previous: 'Zurück', empty: 'In dieser Ansicht sind keine Spiele verfügbar.', noTable: 'Für diesen Wettbewerb und diese Saison ist keine Tabelle verfügbar.', failed: 'Dieser Bereich konnte nicht geladen werden.', retry: 'Erneut versuchen', team: 'Team', played: 'Sp', won: 'S', drawn: 'U', lost: 'N', goals: 'Tore', difference: 'Diff.', points: 'Pkt', form: 'Form', finished: 'Beendet', live: 'Live', predictions: 'Veröffentlichte Prognosen',
    seoTitle: '{name}: Prognosen, Spiele, Ergebnisse & Statistiken', seoDescription: 'Entdecke Prognosen, kommende Spiele, letzte Ergebnisse, die Tabelle und Fußballstatistiken für {name} auf MyBetOracle.', fixturesHeading: 'Spielplan', statisticsHeading: 'Statistiken',
    matchesPlayed: 'Gespielte Spiele', avgGoalsPerMatch: 'Tore pro Spiel (Ø)', homeWin: 'Heimsieg', draw: 'Unentschieden', awayWin: 'Auswärtssieg', btts: 'Beide Teams treffen', over15: 'Über 1,5 Tore', over25: 'Über 2,5 Tore', over35: 'Über 3,5 Tore', avgHomeGoals: 'Heimtore (Ø)', avgAwayGoals: 'Auswärtstore (Ø)', statsUnavailable: 'Für verlässliche Statistiken liegen diese Saison noch nicht genug ausgetragene Spiele vor.' },
  it: { season: 'Stagione', results: 'Risultati', recent: 'Ultimi risultati', next: 'Avanti', previous: 'Indietro', empty: 'Nessuna partita disponibile in questa vista.', noTable: 'Classifica non disponibile per questa competizione e stagione.', failed: 'Impossibile caricare questa sezione.', retry: 'Riprova', team: 'Squadra', played: 'PG', won: 'V', drawn: 'N', lost: 'P', goals: 'GF:GS', difference: 'DR', points: 'Pt', form: 'Forma', finished: 'Terminata', live: 'Live', predictions: 'Pronostici pubblicati',
    seoTitle: '{name}: Pronostici, Partite, Risultati e Statistiche', seoDescription: 'Scopri pronostici, prossime partite, ultimi risultati, classifica e statistiche calcistiche di {name} su MyBetOracle.', fixturesHeading: 'Calendario', statisticsHeading: 'Statistiche',
    matchesPlayed: 'Partite giocate', avgGoalsPerMatch: 'Media gol a partita', homeWin: 'Vittoria in casa', draw: 'Pareggio', awayWin: 'Vittoria in trasferta', btts: 'Entrambe le squadre segnano', over15: 'Over 1,5 gol', over25: 'Over 2,5 gol', over35: 'Over 3,5 gol', avgHomeGoals: 'Media gol in casa', avgAwayGoals: 'Media gol in trasferta', statsUnavailable: 'Non ci sono ancora abbastanza partite giocate in questa stagione per statistiche affidabili.' },
  pt: { season: 'Temporada', results: 'Resultados', recent: 'Últimos resultados', next: 'Próximo', previous: 'Anterior', empty: 'Nenhuma partida disponível nesta visualização.', noTable: 'Classificação indisponível para esta competição e temporada.', failed: 'Não foi possível carregar esta seção.', retry: 'Tentar novamente', team: 'Time', played: 'J', won: 'V', drawn: 'E', lost: 'D', goals: 'GP:GC', difference: 'SG', points: 'Pts', form: 'Forma', finished: 'Encerrado', live: 'Ao vivo', predictions: 'Palpites publicados',
    seoTitle: '{name}: Palpites, Jogos, Resultados e Estatísticas', seoDescription: 'Explore palpites, próximos jogos, últimos resultados, classificação e estatísticas de futebol de {name} no MyBetOracle.', fixturesHeading: 'Próximos jogos', statisticsHeading: 'Estatísticas',
    matchesPlayed: 'Jogos disputados', avgGoalsPerMatch: 'Média de gols por jogo', homeWin: 'Vitória em casa', draw: 'Empate', awayWin: 'Vitória fora', btts: 'Ambos marcam', over15: 'Mais de 1,5 gols', over25: 'Mais de 2,5 gols', over35: 'Mais de 3,5 gols', avgHomeGoals: 'Média de gols em casa', avgAwayGoals: 'Média de gols fora', statsUnavailable: 'Ainda não há partidas suficientes disputadas nesta temporada para estatísticas confiáveis.' },
};
